vault:
   image: vault:1.13.3
   container_name: integra-vault
   restart: always
   environment:
      VAULT_ADDR: http://127.0.0.1:8200
   ports:
      - 8200:8200
   volumes:
      - ./integra-vault-data:/vault/file:rw
      - ./vault:/vault/config:rw
   cap_add:
      - IPC_LOCK
   entrypoint: vault server -config=/vault/config/vault.json
